// Auto-generated by fetch_lp_data.py
// Updated: 2026-05-05T07:30:00
window.PHL5_DATA = {
  "lpVolume":    150948,
  "lpUPH":       0,
  "backlog":     0,
  "cell":        "HA64",
  "lastUpdated": "2026-05-05T07:30:00",
  "skipped":     false
};
