// Auto-generated by fetch_hourly.py
// Updated: 2026-05-06T02:09:56
window.PHL5_DATA = {
  "lpVolume": 0,
  "lpUPH": 0.0,
  "backlog": 0,
  "blNotShipped": 0,
  "blLoaded": 0,
  "blDiverted": 0,
  "blShipLabel": 0,
  "actualVol": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "asrsUPH": [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "boxUPH": [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "actualBag": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "hoursWorked": [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  "capacity": [
    {
      "type": "1P",
      "pool": 1,
      "planned": 0,
      "consumed": 0,
      "available": 0,
      "color": "#0053e2"
    },
    {
      "type": "3P/WFS",
      "pool": 4,
      "planned": 0,
      "consumed": 0,
      "available": 0,
      "color": "#ffc220"
    },
    {
      "type": "SAMS",
      "pool": 27,
      "planned": 0,
      "consumed": 0,
      "available": 0,
      "color": "#2a8703"
    }
  ],
  "otsData": [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
  "cellVol": "HA64",
  "cellUPH": "HA69",
  "lastUpdated": "2026-05-06T02:09:56",
  "skipped": false
};
