#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["msal", "requests"]
# ///
"""
PHL5 Dashboard — Backlog Fetcher
Runs every 15 min Mon–Thu 07:30–18:00 via Task Scheduler.
Formula: Backlog = Not Shipped − Loaded − Diverted − Ship Label Applied
Source: Endgame FC 3124 — https://endgame.prod.mase.glb.us.walmart.net/3124/pt-status
"""

import json, msal, requests, urllib3
from datetime import date, datetime
from pathlib import Path

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

HERE       = Path(__file__).parent
DATA_JS    = HERE / "data.js"
EG_CACHE   = HERE / ".token_cache_endgame.json"
TENANT_ID  = "3cbcc3d3-094d-4006-9849-0d11d61f484d"
EG_CLIENT  = "777d5c3a-eb0c-43d5-b30a-798a7eb9d15e"
EG_SCOPES  = [f"{EG_CLIENT}/.default"]
FC_ID      = "3124"

EG_ENDPOINTS = [
    f"https://flow-management-api.endgame-orderpooling.prod.k8s.walmart.net/v1/{FC_ID}/flow-management/shift/recommendations",
    f"https://status-api.endgame-status.prod.k8s.walmart.net/v3/{FC_ID}",
    f"https://status-api.endgame-status.prod.k8s.walmart.net/v1/api/pt-status/fc-id/{FC_ID}/summary",
    f"https://status-api.endgame-status.prod.k8s.walmart.net/v1/api/pt-status/fc-id/{FC_ID}",
]


def get_token() -> str:
    cache = msal.SerializableTokenCache()
    if EG_CACHE.exists():
        cache.deserialize(EG_CACHE.read_text())

    app = msal.PublicClientApplication(
        EG_CLIENT,
        authority=f"https://login.microsoftonline.com/{TENANT_ID}",
        token_cache=cache,
    )

    result = None
    accounts = app.get_accounts()
    if accounts:
        result = app.acquire_token_silent(EG_SCOPES, account=accounts[0])

    if not result or "access_token" not in result:
        # First-time / expired — device code flow
        flow = app.initiate_device_flow(scopes=EG_SCOPES)
        print("\n" + "="*60)
        print("🔐 One-time login required:")
        print(f"   Open: {flow['verification_uri']}")
        print(f"   Code: {flow['user_code']}")
        print("="*60 + "\n")
        result = app.acquire_token_by_device_flow(flow)

    if "access_token" not in result:
        raise RuntimeError(f"Auth failed: {result.get('error_description')}")

    if cache.has_state_changed:
        EG_CACHE.write_text(cache.serialize())

    return result["access_token"]


def fetch_backlog(token: str) -> int:
    headers = {"Authorization": f"Bearer {token}", "Accept": "application/json"}

    for url in EG_ENDPOINTS:
        try:
            r = requests.get(url, headers=headers, timeout=12, verify=False)
            if r.status_code != 200:
                continue
            data = r.json()

            # flow-management/shift/recommendations → backlog array
            if "backlog" in data and isinstance(data["backlog"], list):
                return sum(b.get("units", 0) for b in data["backlog"])

            # pt-status summary → individual status counts
            if any(k in data for k in ("notShipped", "not_shipped")):
                ns  = data.get("notShipped", data.get("not_shipped", 0))
                ld  = data.get("loaded", 0)
                div = data.get("diverted", 0)
                sla = data.get("shippingLabelApplied", data.get("ship_label_applied", 0))
                return max(0, int(ns) - int(ld) - int(div) - int(sla))

            # GetShiftSetup → overdueUnits sum
            if "processPathList" in data:
                return sum(p.get("overdueUnits", 0) for p in data["processPathList"])

        except Exception:
            continue

    return 0   # fallback — keeps existing value


def patch_data_js(backlog: int):
    """Read existing data.js, update only the backlog field, rewrite."""
    current = {}
    if DATA_JS.exists():
        txt = DATA_JS.read_text(encoding="utf-8")
        # Extract the JSON object from the JS file
        start = txt.find("{")
        end   = txt.rfind("}") + 1
        if start != -1 and end:
            try:
                current = json.loads(txt[start:end])
            except Exception:
                pass

    current["backlog"]     = backlog
    current["lastUpdated"] = datetime.now().isoformat(timespec="seconds")

    ts = current["lastUpdated"]
    DATA_JS.write_text(
        f"// Auto-generated by fetch_backlog.py\n"
        f"// Updated: {ts}\n"
        f"window.PHL5_DATA = {json.dumps(current, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"✅ Backlog={backlog:,} written → {DATA_JS.name}")


def main():
    today = date.today()
    if today.weekday() > 3:
        print("Not a shift day — skipping.")
        return

    print(f"🔄 Backlog fetch — {datetime.now().strftime('%H:%M:%S')}")
    token   = get_token()
    backlog = fetch_backlog(token)
    patch_data_js(backlog)


if __name__ == "__main__":
    main()
